# List work as Queue (FIFO) deque (Class)
from _collections import deque
List=deque()
List.append(10)
print(List)
print(list(List))
List.append(20)
print(list(List))
List.append(30)
print(list(List))
List.append(40)
print(list(List))
List.append(50)
print(list(List))

List.popleft()
print(list(List))
List.popleft()
print(list(List))
List.popleft()
print(list(List))
List.popleft()
print(list(List))

